### ISSUE TITLE
Вывести блок читать далее с 3 случайными ссылками

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#112]
Вывести под статьёй три случайные ссылки на статьи.

**Comment by n0str** [comment]
Задача не ясна. Проставьте Labels. Это дизайн, верстка, backend? Или все сразу?

**Comment by eliseealex** [comment]
Поставил

**Comment by illiiiillllilii** [comment]
Зачем выводить именно случайные статьи, если это можно проконтролировать и выводить, например, малочитаемые статьи или 1 популярную и две, к которым стоит привлечь внимание?
