### ISSUE TITLE
Backend раздела "Contests"

### ISSUE THREAD

**Issue by n0str** [codex-team/codex#118]
Описание общей задачи: #116 

С точки зрения функционала, вопросов никаких возникнуть не должно.
С точки зрения DB, думаю, нужна отдельная таблица Contests с очевидными полями.

**Comment by neSpecc** [comment]
Задание более подробно

 # Форма создания конкурса, которая сохраняет его в базу
* Заголовок конкурса
* Подробное описание
* Описание приза
* Дата создания
* До какой даты действует
* Статус: открыт/закрыт
* ID победителя

# Вывод списка конкурсов на странице с адресом `/contests/`

# Просмотр отдельного конкурса
