### ISSUE TITLE
Встроить редактор на сайт

### ISSUE THREAD

**Issue by n0str** [codex-team/codex#122]
Самую первичную версию редактора, чтобы было хотя-бы от чего стартовать.

**Comment by n0str** [comment]
Under hard development: https://github.com/codex-team/codex/tree/codex-editor

**Comment by loopdigga98** [comment]
@n0str ссылка выдает 404

**Comment by n0str** [comment]
@loopdigga98 залил заново

**Comment by n0str** [comment]
@khaydarov  Не закрыто еще?

**Comment by khaydarov** [comment]
еще нет. Сейчас работает только ifmo.su/editor. Там можно написать статью и посмотреть как выглядит JSON.
