### ISSUE TITLE
Бот, который присылает инфу о статистике сайта в чат телеграма в 24:00

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#130]

**Comment by n0str** [comment]
А откуда статистику брать?
Вижу реализацию через curl

**Comment by neSpecc** [comment]
из API метрики или ga

**Comment by n0str** [comment]
@neSpecc скинь мне пожалуйста в телеграм api ключ от яндекс метрики или что там еще нужно.

**Comment by loopdigga98** [comment]
@n0str @neSpecc кто нибудь делает эту задачу? я бы хотел попробовать
