### ISSUE TITLE
Система алиасов

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#142]
Нужно продумать и разработать систему роутинга на сайте по схеме `ifmo.su/title-of-subject` , где после первого слэша сразу идет название сущности (статьи, конкурса, пользователя и любой другой)

### Пример реализации
Подобная система работает на сайте американского анжел-листа для стартапов:
- https://angel.co/meerkat —стартап
- https://angel.co/itai-danino — пользователь
- https://angel.co/php — рабочий навык
- https://angel.co/russia — страна
- https://angel.co/moscow — город

### Основная проблема
Определить, с какой сущностью мы имеем дело и направить в нужный контроллер.

### Решение
В специальной таблице алиасов будут храниться соответствия uri-строки и сущности.
```
id   uri   hash   type   target   dt_add
```
где 
**uri** — строка из адреса
**hash** — цифровой хэш от uri для более быстрого поиска (см. Особенности реализации)
**type** — тип сущности (например «Конкурс», «Статья» , «Пользователь» и тд) хранится в виде цифровых констант
**target** — указатель на сущность. То есть id конкурса, статьи, пользователя и тд

Потребуется добавить во все функции создания сущностей (новая статья, новый конкурс, регистрация пользователя и тд) метод, который будет записывать эту сущность в таблицу алиасов.

### Коллизии
Известной проблемой являются коллизии — ситуации, когда одному названию может соответствовать несколько сущностей. Например, *ifmo.su/victory* может быть и пользователем, и конкурсом, и статьей и любой другой сущностью

Решать коллизии будем самым простым способом: _кто первый занял uri, тому он и принадлежит_. К остальным будет дописывается численный указатель, например */victory-1* , */victory-2* и тд

### Ограничения
1. Нужно заранее составить список запрещенных uri, которые могут быть использованы системой. Например: admin, auth, login, signup и тд
2. Минимальная длина uri — 3 символа 

### Особенности реализации
1. Таблица алиасов будет довольно быстро разрастаться. Этот вопрос нужно отдельно продумать. 
2. Поиск по типу INT будет работать намного быстрее, чем по CHAR, поэтому каждый uri нужно преобразовывать в хэш-сумму с помощью специального алгоритма. 
3. Нужно реализовать статистику запросов разных URI , чтобы видеть, какие адреса наиболее часто запрашиваются, а какие — редко. В дальнейшем это пригодится для оптимизации.

**Comment by khaydarov** [comment]
Итак, выкладываю уже сделанную работу, но делать пул пока рано. У меня возникли вопросы.
Как быть если строка длинная ? например: ФИО пользователя - 20-25 символов. Если мы хэшируем и берем p > 10, у нас получается BIGINT, а не INT в ДБ. 
В Модели Uri есть метод getAliases() - который выгружает из БД все алиасы и возвращает массив в виде: array([hash]=>[string]), а не array([0]=>array(id, hash, typ.....)). Это потому, чтоб в Controller-e Uri не проверяли поиском по массиву, что может занять не мало времени при больших количеств строк, а проверяю только хэш.
 => request (принимаем экшн)
hash = request->hash() // хэшируем экшн
if (Aliases[hash] != empty) - т.е если есть такой хэш, тогда идем дальше. 
Теперь сам вопрос: А что если хэш-сумма будет большой: 10-15 знаков. Сможем ли также проверять $aliases[$hash] - ?

**Comment by neSpecc** [comment]
Чтобы решить проблему с длинными строками можно их хэшировать, например через sha256, а потом уже получать числовой хэш. 

По поводу `getAliases` не совсем понял. А почему не средствами БД проверять наличие алиаса? мы же для этого и делали числовой хэш
