### ISSUE TITLE
Разработка структуры БД для объединения статей в курсы

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#160]

**Comment by gohabereg** [comment]
Структура таблицы для хранения курсов. Если все ок, сделаю миграцию.
[Courses.docx](https://github.com/codex-team/codex/files/595966/Courses.docx)

Ну и в таблицу статей добавляется поле course_id

**Comment by neSpecc** [comment]
Вроде норм. А что такое marked?

**Comment by gohabereg** [comment]
Отмечает курс как важный. Как со статьями

**Comment by neSpecc** [comment]
А как потом составлять общую ленту статей и курсов?

**Comment by gohabereg** [comment]
Это разве к структуре БД вопрос?
Или ты к тому, что курсы по умолчанию 'важные'?

**Comment by neSpecc** [comment]
С marked я понял. Я просто задумался о формировании общей ленты статей и курсов. Получается, что в обоих таблицах есть order и marked , то есть будут сложности с сортировкой. 

Как вариант, можно добавить в таблицу `Articles` поле `id_parent`, которое позволит вкладывать статьи друг в друга. Если `id_parent != 0` , то это курс. При таком подходе будет меньше проблем с формированием и сортировкой ленты. Но это пока вопрос обсуждения

**Comment by gohabereg** [comment]
Еще вариант сделать таблицу Artcles_Order например. Там хранить курсы и статьи по id с указанием даты создания и order. А выборку делать с сортировкой сначала по order,а потом по дате. Но тут вопрос как хранить id, ведь они могут у курса и статьи совпадать. Как вариант, сделать еще одно поле is_course

**Comment by neSpecc** [comment]
Кстати да, только для этого можно использовать Redis. А именно sorted set 
http://redis.io/topics/data-types#sorted-sets

При создании статьи добавлять ее через `ZADD` и в качестве score использовать таймстамп, например. С помощью этого score можно сортировать их

**Comment by gohabereg** [comment]
Ну а если указали order, то как статью записать в этот список?

**Comment by gohabereg** [comment]
И `parent_id` все таки стоит ввести. Ну или какой-нибудь `coures_order`, чтобы знать в каком порядке статьи в курсе идут

**Comment by neSpecc** [comment]
sorted set редиса может являть собой список статей и курсов, то есть при добавлении статьи или курса можно добавить его в sorted set с нужным порядком
