### ISSUE TITLE
Доработка авторизации через GitHub

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#166]
Обнаружена проблема в классе oauth-авторизации через GitHub
https://github.com/codex-team/codex/blob/master/modules/oauth/classes/Kohana/Oauth/Github.php 

Метод `get_access_token()` , который сперва редиректит на гитхаб с передачей параметров из конфига для получения CODE, который потом подставляется в запрос на получение ACCESS_TOKEN. 

Конец метода, часть с запросом на получение ACCESS_TOKEN и обработкой ответа:
```php
        $params = array(
            'client_id'     => self::$config['APP_ID'],
            'code'          => $params['code'],
            'client_secret' => self::$config['APP_SECRET'],
            'redirect_uri'  => self::$config['REDIRECT_URI']
        );
        $resp = Request::factory(self::$config['GET_TOKEN_URI'])
            ->method(Request::GET)
            ->query($params)
            ->execute();

        parse_str($resp);

        if (!isset($access_token))
        {
            # TODO: Throw custom Exception for GitHub
            throw new Kohana_Exception('Error: '.$resp->error.' Description: '.$resp->error_description);
        }
        $this->token = $access_token;

        return true;
```

Как видно, ответ помещается в `$resp` , которая потом с помощью `parse_str` преобразуется в переменные ($access_token). Это подразумевает, что в ответе придет поле `&access_token=<token>` , иначе переменная с таким названием не создастся. 

На проде сейчас это почему-то работает, но на стейдже была обнаружена проблема, что от гитхаба приходит ответ такого вида: 

```php
object Response(5) {
    protected _status => integer 200
    protected _header => object HTTP_Header(18) {
        public server => string(10) "GitHub.com"
        public date => string(29) "Sat, 26 Mar 2016 16:41:08 GMT"
        public content-type => string(48) "application/x-www-form-urlencoded; charset=utf-8"
        public transfer-encoding => string(7) "chunked"
        public status => string(6) "200 OK"
        public cache-control => string(8) "no-cache"
        public vary => array(2) (
            0 => string(6) "X-PJAX"
            1 => string(15) "Accept-Encoding"
        )
        public x-ua-compatible => string(16) "IE=Edge,chrome=1"
        public x-request-id => string(32) "a5c7e20af93092fbb35429b36fffef89"
        public x-runtime => string(8) "0.018444"
        public content-security-policy => string(876) "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com api.braintreegateway.com client-analytics.braintreegateway.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.gravatar.com *.wp.com checkout.paypal.com *.githubusercontent.com; media-src 'none'; object-src assets-cdn.github.com; plugin-types application/x-shockwave-flash; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com; report-uri https://api.github.com/_private/browser/errors"
        public strict-transport-security => string(44) "max-age=31536000; includeSubdomains; preload"
        public public-key-pins => string(447) "max-age=1209600; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains"
        public x-content-type-options => string(7) "nosniff"
        public x-frame-options => string(4) "deny"
        public x-xss-protection => string(13) "1; mode=block"
        public x-served-by => string(32) "a568c03544f42dddf712bab3bfd562fd"
        public x-github-request-id => string(30) "5BDAE73A:38F3:7F0E5E8:56F6BBA4"
    }
    protected _body => string(78) "access_token=04daae52ab807b1d2a8343a97f66866092066991&scope=&token_type=bearer"
    protected _cookies => array(0) 
    protected _protocol => NULL
}
```

То есть это целиком объект Request , который и передается в parse_str. Однако туда нужно передавать только тело ответа `_body` , тк именно оно содержит нужные данные. 

Из-за этого не создавалась переменная $access_token и не работала авторизация.

Проблема решилась добавлением к конструктору `Request` курсора `->body()`, который поместил в переменную $resp не весь объект, а только тело ответа: 

```php
$resp = Request::factory(self::$config['GET_TOKEN_URI'])
            ->method(Request::GET)
            ->query($params)
            ->execute()
            ->body();
```

Возможно, так и задумано было, но момент был упущен. Надо разобраться и внести правки. 

А еще я бы убрал parse_str и сделал более очевидное присваивание переменной $access_token.

**Comment by n0str** [comment]
> То есть это целиком объект Request , который и передается в parse_str. Однако туда нужно передавать только тело ответа _body , тк именно оно содержит нужные данные.

parse_str принимает строку в качестве аргумента. Объект Request после преобразования в строку, возвращает _body. Это можно проверить через `echo $resp;`

С точки зрения безопасности использовать parse_str неправильно. Для этого можно использовать второй параметр: `parse_str($resp, $results);` и потом обращаться к нему как `$access_token = $results['access_token']`

Но как такового бага я тут не вижу, очевидно, на stage проблема заключалась в чем-то другом. Может конфиг не верный?

**Comment by neSpecc** [comment]
конфиги я сто раз проверил

Давай сделем с `$results['access_token']` ? А еще было бы неплохо добавить нормальную обработку ошибок. А то сейчас есть проверки, в которых else никак не обрабатывается

**Comment by neSpecc** [comment]
тем более access_token то приходит , просто код не правильно отрабатывает
