### ISSUE TITLE
Макет страницы статьи, входящей в курс

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#248]
Пользователь должен понимать, что статья является частью курса. 
Видеть название курса, предыдущие и следующие части.

**Comment by neSpecc** [comment]
![courses_game_sketch2](https://cloud.githubusercontent.com/assets/3684889/20358635/a57bc074-ac3d-11e6-9f2d-327c55fa1315.png)

Доработать: 

- Должны быть видны все статьи, входящие в курс

**Comment by dslznv** [comment]
[Макет на Figma](https://www.figma.com/file/O2YfV0geuuBmzaqguiCRsWgT/CodeX.-%D0%A1%D1%82%D0%B0%D1%82%D1%8C%D1%8F-%D0%B8-%D0%B8%D0%B3%D1%80%D0%B0)
