### ISSUE TITLE
Разработать схему JS модуля тестирования

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#254]

**Comment by gohabereg** [comment]
Набросал схемку для вывода теста

Сценарий:
https://docs.google.com/document/d/1WINjLQ8qwRGIC7LxoEWV1YY8kbEnRm6lIAfSNbMsj5s/edit?usp=sharing

Схема:
https://drive.google.com/open?id=0B8lxt2zEKVPJVnBoWk1EUDctU0U

Структура входных данных:
https://drive.google.com/open?id=0B8lxt2zEKVPJeFR3WWxHVVBVZjQ

**Comment by gohabereg** [comment]
Обновил схемы, открываются с помощью draw.io

https://drive.google.com/file/d/0B8lxt2zEKVPJT3JlZVN3c2NwRVE/view?usp=sharing

https://drive.google.com/file/d/0B8lxt2zEKVPJTTdNUTc2azBSUEk/view?usp=sharing

**Comment by gohabereg** [comment]
Входные данные
![gamedata](https://cloud.githubusercontent.com/assets/23050529/20631152/430efea0-b346-11e6-97ee-b47566668b36.png)

Модуль
![gamemodule](https://cloud.githubusercontent.com/assets/23050529/20631230/a745e140-b346-11e6-96ba-c2c61e6bbc26.png)
