### ISSUE TITLE
Разработать систему автоматических ежедневных бэкапов 

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#293]
- MySQL
- uploads
- Redis

на всех проектах

**Comment by n0str** [comment]
Набросал скриптик для яндекс.диска. Позволяет загружать MySQL.
Для redis можно использовать https://github.com/nullptr-cc/php-redis-dump
Для uploads можно делать tar.gz архив и отправлять на яндекс диск каждые сутки. Отдельным скриптом можно удалять старые uploads каждую неделю, оставляя только последний самый свежий.

**Comment by n0str** [comment]
Готово. Надо бы оформить в виде короткой статьи или модуля.

**Comment by n0str** [comment]
Развернуть на новом сервере и закрыть ISSUE
