### ISSUE TITLE
Баги с алиасами пользователей

### ISSUE THREAD

**Issue by gohabereg** [codex-team/codex#301]
1. Авторизированный пользователь при переходе по любому алиасу пользователя попадает на свою страницу.
2. Неавторизованный пользователь при переходе по алиасу пользователя (или по user/id пользователя с алиасом) получает 404 ошибку.

**Comment by n0str** [comment]
Предлагаю воспроизвести данный баг, описать его и я готов фиксить.
Кто возьмётся описать последовательность действий для бага? @talyguryn

**Comment by gohabereg** [comment]
Вариант первый:
Незалогинившийся юзер (или юзер без алиаса) заходит на страницу к пользователю с алиасом. Вылетает 404
![image](https://cloud.githubusercontent.com/assets/23050529/22518459/b0f3f266-e8bd-11e6-8061-ddfa0cb3a72a.png)

При этом не важно, заходит ли он через /alias или /user/id, все равно вылетит 404, тк идет редирект на алиас.

Вариант второй:
Залогинившийся юзер с алиасом заходит на страницу к пользователю с алиасом. Попадает на свою страницу (в адресе остается алиас, на который переходили).
