### ISSUE TITLE
Дизайн 404 и 500

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#35]

**Comment by illiiiillllilii** [comment]
Надо бы привязаться с обычным шаблонам для страницы views/main.php и точно так же передать все проблемы в $content
Чтобы что-то подобное получить
<img width="1090" alt="screen shot 2015-12-08 at 18 21 32" src="https://cloud.githubusercontent.com/assets/15259299/11659292/8e4f467e-9dd8-11e5-806c-38e88a1b8fb3.png">

**Comment by neSpecc** [comment]
что-то типа того. Только дизайн у тебя не красивый.
И еще в main.php используется несколько глобальных переменных из предиспатча, которых не будет при возникновении ошибки. 
Так что я думаю пока сделаем проще, без обертки. Она не особо нужна.
Задача на мне, я уже начинал, но пока не коммитил

**Comment by neSpecc** [comment]
буду делать эту задачу совместно с ботом для телеграма

**Comment by aripdotcom** [comment]
http://megamozg.ru/company/triggmine/blog/22760/

**Comment by talyguryn** [comment]
ап

**Comment by n0str** [comment]
Что значит ап? Давай реквест? :)
