### ISSUE TITLE
Добавлять дату модификации

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#38]

**Comment by ivanszhuravlev** [comment]
#54

**Comment by eliseealex** [comment]
Не понятно, как должна выглядеть дата, нужно обсудить и решить

**Comment by eliseealex** [comment]
Изменять только при езменении тригера и заголовка

**Comment by ivanszhuravlev** [comment]
@eliseealex, а нужно удалять старый триггер?

**Comment by eliseealex** [comment]
Имеет смысл делать эту задачу после того, как будет добавлено редактирования. Заблокирована задачей #48.

**Comment by neSpecc** [comment]
Мы решили делать средствами mysql `now()`
