### ISSUE TITLE
Добавить возможность редактировать статью

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#48]

**Comment by illiiiillllilii** [comment]
Предлагаю использовать ту же форму, что и для создания статьи.
Если статья существует, у неё есть id, который мы передаём в форму.
Ну и напоследок. Если в $_POST есть id статьи, то мы обновляем информацию. Иначе  просто добавляем новую статью

**Comment by n0str** [comment]
Ну это правильно, использовать форму повторно. Можно вынести форму в отдельную view и использовать ее как вложенную в view update и view create. Это довольно удобный подход, который используется в yii2

**Comment by eliseealex** [comment]
Да, тоже согласен, только пока что у нас нет формы создания статьи, так что ждём пока что эту задачу не сделать

**Comment by eliseealex** [comment]
Ждём редактора
