### ISSUE TITLE
CodeX Lab landing page implementation

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex#618]
1. UI: https://zpl.io/bAxoLPO
2. Шапка и футер должно быть наши стандартные, только покрашенные в цвет лендинга, как на [codex.so/media](codex.so/media)
3. Пункты в секции "Full cycle of product making" должны появляться при доскроле до секции
4. Пункты в секции "Full cycle of product making" должны появляться с анимацией один за другим, при этом  прямоугольники появляются вместе с каждым пунктом, тоже с анимацией
5. Аналогично в секции "Find a role and lead it" — пункты появляются с анимацией, по очереди, вместе со звездочками, при доскроле до секции
6. Нужно создать ящик lab@codex.so
7. Форма отправки заявки должна работать. Надо предусмотреть валидацию полей, вид у неавторизованного/авторизованного, сообщение об успешной отправке; состояние, когда заявка уже отправлена.

**Comment by talyguryn** [comment]
#625

**Comment by talyguryn** [comment]
resolved
