### ISSUE TITLE
Добавить алиасы для статей

### ISSUE THREAD

**Issue by n0str** [codex-team/codex#63]
Обсуждалось, что в алиасе будет обязательно фигурировать id статьи, по которому на самом деле будет происходить поиск.
URL может быть нескольких видов:
* https://ifmo.su/articles/24/new-best-php-framework/
* https://ifmo.su/articles/new-best-php-framework-24/
* https://ifmo.su/articles/new-best-php-framework/24/

Как по мне - так первый вариант лучший.

**Comment by n0str** [comment]
Нашел еще более крутой вариант:
https://ifmo.su/articles/24-new-best-php-framework

**Comment by Markus3295** [comment]
> https://ifmo.su/articles/24/new-best-php-framework/
https://ifmo.su/articles/new-best-php-framework/24/

эти два как подразделы для поисковиков - не ок


> https://ifmo.su/articles/new-best-php-framework-24/

этот выглядит, как-будто 24 относится к самому названию, а это не так

> https://ifmo.su/articles/24-new-best-php-framework

итого я за этот

**Comment by neSpecc** [comment]
>https://ifmo.su/articles/new-best-php-framework-24/
>https://ifmo.su/articles/24-new-best-php-framework/
Это выглядит как часть статьи и вводит в заблуждение. Особенно, когда заголовок начинается или кончается цифрами

Я за `https://ifmo.su/articles/24/new-best-php-framework/`

**Comment by illiiiillllilii** [comment]
А как тогда ловить эти адреса?
https://ifmo.su/articles/24/edit
https://ifmo.su/articles/24/delete

**Comment by neSpecc** [comment]
отдельными роутами
`/articles/<id>/add`
`/articles/<id>/edit`
`/articles/<id>/remove`

**Comment by n0str** [comment]
Можно посмотреть, как это реализовано у топовых площадок.

**Comment by neSpecc** [comment]
у медузы и ленты id не используется. Поиск идет по uri, замена буквы ведет к 404. Поддержка редактирования названия — неизвестно. Либо они сохраняют старые uri , либо отдают 404 по ссылкам со старым названием. 

у Forbes по схеме  `/134543-uri`

tj, vc пишут вручную, все uri уникальные

Дождь по схеме `/uri-1425654`

На Спарке схема `/id/uri`

**Comment by n0str** [comment]
RT пишет как Марк хотел :D

**Comment by eliseealex** [comment]
Я за 
https://ifmo.su/articles/new-best-php-framework-24/

https://ifmo.su/articles/24-new-best-php-framework/
читается как 24 новых лучших пхп-фреймворка.

**Comment by n0str** [comment]
Ссылка в конце неудобна при передачи URL. Если он длинный - долго будет крутить и ее выделять, чтобы получить короткий линк, ну или при копировании может куда-нибудь потеряться, а она важнее самого текста.

**Comment by eliseealex** [comment]
Есть в этой мысли логика, но по такому же принципу можно сказать, что GET-параметры — зло. Стоит думать, что интересно пользователю. 24 — это дырявая абстракцию, которая раскрывает нашу внутреннюю реализацию, стоит стремиться её спрятать. Да и вообще роут articles — тоже дырявая абстракцию, будто бы в модуле статей есть ещё что-то важное, кроме статей. Стоит отталкиваться от целей нашего сайта. 

Идеальный вариант — это всё-таки https://ifmo.su/new-best-php-framework/, согласитесь? Мы не хотим повторять статьи, поэтому не стоит пытаться добавлять уникальности к этому заголовку. Вопрос того, чтобы хранить несколько ссылок на одну таблицу решается простой таблицой базы данных с индексом. Может не стоит ничего усложнять с точки зрения пользователя? У нас маленький урл и пользователь сможет запомнить название ссылки полностью: ifmo.su/python-bot или ifmo.su/2016.

**Comment by n0str** [comment]
Мне нравится идея с алиасами без ID. Возможно, стоит ее реализовать на первое время и посмотреть в динамике плюсы и минусы.

**Comment by illiiiillllilii** [comment]
Слишком много разных идей. С чего стоит начать?

**Comment by n0str** [comment]
Илея с алиасами без ID хороша, начал бы с нее. А тут нельзя ставить на голосование? :)

**Comment by illiiiillllilii** [comment]
Нам же нужно правильное и обоснованное решение, а не мнение большинства
У каждой идеи есть плюсы и минусы

**Comment by n0str** [comment]
Всегда есть как минимум несколько правильных решений. Давайте перенесем дискуссию в телеграм

**Comment by neSpecc** [comment]
предлагаю ради опыта реализовать ссылки вида `ifmo.su/telegram-bot` с сохранением предыдущих названий

**Comment by neSpecc** [comment]
только нужно учесть, что и конкурсы (и другие сущности) тоже будут иметь такие же роуты и сайт должен научиться определять где что

**Comment by neSpecc** [comment]
Задача переросла в https://github.com/codex-team/codex/issues/142
