### ISSUE TITLE
Разобраться с 404 ошибкой [solved]

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#80]
Когда бросаешь Kohana 404 Exception, отображается кохановская страница с 404 ошибкой, а не наша, нужно разобраться, почему так получается и вернуть нашу ошибку. Пример можно посмотреть по https://ifmo.su/article/1311

**Comment by n0str** [comment]
И вообще на любом роуте сломанном отображается debug: https://ifmo.su/a123

**Comment by illiiiillllilii** [comment]
6 дней уже. Есть продвижения?

**Comment by loopdigga98** [comment]
Нужно поменять режим разработки приложения, по умолчанию включен режим Development.

**Comment by loopdigga98** [comment]
Close #80
