### ISSUE TITLE
После авторизации оставаться на той же странице

### ISSUE THREAD

**Issue by eliseealex** [codex-team/codex#92]

**Comment by illiiiillllilii** [comment]
Можно с помощью get передать кусок адреса

**Comment by n0str** [comment]
Посмотрел исходники Yii2. Есть два варианта:

1) Запоминать ReturnUrl в сессии

2) Воспользоваться HTTP Referer 

Оба варианта имеют преимущества, я отдаю предпочтение второму т.к., он сработает в большинстве случаев и не требует изменений кода кроме 1 строчки.
